### ISSUE TITLE
if part name is exact then should return the exact part

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SBOLExplorer#62] opened 2020-05-16 19:16 UTC
It is really annoying that if you type in an exact BBa_.... it is not the first result.

**Comment by cjmyers** [comment] 2020-05-18 20:43
This issue relates to #28.  Namely, what is happening is PageRank score is shifting some matches above the exact match.  This is done because it allows for mis-spellings to still be picked up.  Case in point, if you search BBa_F2260 you get the more popular result of BBa_F2620 reflecting that you likely mis-typed.  That being said, it may be worth experimenting with the weightings to see if there is a better mix that gives more expected results.  Closing this issue, since it is effectively a duplicate of #28.

**Closed by cjmyers** 2020-05-18 20:43 UTC
